language: scala
scala:
- 2.11.6
- 2.10.4
jdk:
- oraclejdk7
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/20b8e51c61363eee95e8
    on_success: change
    on_failure: always
    on_start: false
  email:
  - truffaut.julien@gmail.com
script: sbt ++$TRAVIS_SCALA_VERSION test
env:
  global:
  - secure: JjrFp+1hGEwifDp5vh9BZ4vlZKe/zg/KbGg57PuCtsEgOvpUhvu0Fl6b3JImmF8GKZNjhk2EcgWAA8wyROIORVYNVaroOTHf/XoLvrHhgskGpx042O3gDuiufAaItUGN6NWXB/IjafP69Y1OWDocOsDWRJuL7f/9uom9aKdpamM=
  - secure: bNUYybjKmsptOCsOsgEX29WKPwSZQP9N9fKAyyc/zIIq4tyAr5mJ/v3YRdEB7n2F7cnpNJQqUZ5llQdNGeFUNb2YycbWzTbA2zQmuoI3pawaUwDii57yOMd+E0I21eiok6eXaMlm9RzOBJ8iRwO9uL7QnUPuNqXbUwNT2zkspS4=

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"
