language: scala

scala:
- 2.13.0-RC1
- 2.12.8

jdk:
- oraclejdk8

before_install:
- git fetch --tags
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.3.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.8.3

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)


jobs:
  include:
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/$PRE
        - sbt ++$TRAVIS_SCALA_VERSION monocle${TARGET}/test packageSrc
    - stage: release
      script: sbt ci-release


after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishMicrosite.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
  deploy and release"; fi

env:
  global:
    - secure: lJxaR+9VM96s7rfaigL3K2FbcP3XiZ+AerbgOBOpYi2anRkMPQ91h1g60HYTwEDGJIKybyNWFuXZM8hNtQMCxzxgu7ev1SyRr5Otfzg5ehGqB5UWbSAgpXlqhR5dAonwmqyEEDF2OK+k1fa0N6mIwpQeuUCwrt68kTp4f0K9jMQ=
    - secure: NZQn8lB04I+FO3Om680CXWP29scS/zRhITbLO/1sM3dnuG8ygn0fzlFMQhgCO3fCjnclThAi+6MN7UnyV8BwDbFhCDe627+06px5fHUw2TPdzhz/BwngAW9pRsx6m0b8eBqQmt8Q6mlgeYOPemsFOeqQTKZulpIhSYnO1R1Nwzc=
  matrix:
    - TARGET=JVM PRE=test:compile
    - TARGET=JS  PRE=test:fastOptJS

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt